name: "Delete Merged Branches"

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: jessicalost/delete-merged-branch@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}